### ISSUE TITLE
Time command response in analogue format?

### ISSUE THREAD

**Issue by Webx123** [TechWhizZ199/pinybot#17]
it says ex: : 11:02 no am or pm anyway to make it say am or pm in the time?

**Comment by Autotonic** [comment]
It's in 24hr format

**Comment by TechWhizZ199** [comment]
Should it be kept in 24 hour format?

**Comment by Webx123** [comment]
Very few people use army time id make !time 12 hour and !time+ 24 hr or vise

**Comment by Autotonic** [comment]
Yes it should be 24hr time.

**Comment by TechWhizZ199** [comment]
We'll leave it in 24 hour format for now.

**Comment by notnola** [comment]
Most countries use 24 hour time, thus there will be no official support for 12 hour time. However, feel free to make a pull request with the modifications and it will be reviewed promptly.
